[project]
name = "OpinionList"
version = "0.0.1"
description = "AI-powered sentiment analysis with reproducible models and scalable deployment."
readme = "README.md"
requires-python = ">=3.13.3"
dependencies = [
    "fastapi>=0.123.5",
    "mlflow>=3.6.0",
    "scikit-learn>=1.7.2",
    "torch>=2.9.1",
    "uvicorn>=0.38.0",
]
