global:
  scrape_interval: "15s"
  evaluation_interval: "15s"

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ["prometheus.docker-net:9090"]

  - job_name: node
    static_configs:
      - targets: ["node-exporter.docker-net:9100"]

  - job_name: traefik
    static_configs:
      - targets: ["traefik.docker-net:8080"]

  - job_name: grafana
    static_configs:
      - targets: ["grafana.docker-net:3000"]

  - job_name: postgres
    static_configs:
      - targets: ["postgres-exporter.docker-net:9187"]
