apiVersion: 1

datasources:
  - name: Prometheus
    url: http://prometheus.docker-net:9090
    type: prometheus
    access: proxy
    uid: prometheus
    basicAuth: true
    basicAuthUser: admin
    secureJsonData:
      basicAuthPassword: $PROMETHEUS_PASSWORD
